---

- name: Install Firefox
  win_chocolatey:
    name: firefox
    state: present
    architecture: x86
    version: 38.0.5
    pinned: yes

- name: Copy override.ini
  win_copy:
    src: "files/override.ini"
    dest: 'C:\Program Files\Mozilla Firefox\override.ini'
    
- name: Copy local-settings.js
  win_copy:
    src: "files/local-settings.js"
    dest: 'C:\Program Files\Mozilla Firefox\defaults\pref\local-settings.js'

- name: Copy mozilla.cfg
  win_copy:
    src: "files/mozilla.cfg"
    dest: 'C:\Program Files\Mozilla Firefox\mozilla.cfg'

- name: Make Firefox the default browser
  win_command: '"C:\Program Files\Mozilla Firefox\uninstall\helper.exe" "/SetAsDefaultAppGlobal"'